{% set name = "eth-hash" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ae72889e60db6acbb3872c288cfa02ed157f4c27630fcd7f9c8442302c31e478

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5,<4.0
    - setuptools-markdown
    - pycryptodome
  run:
    - python >=3.5,<4.0
    - pycryptodome >=3.6.6,<4
    - pysha3 >=1.0.0,<2.0.0  # [py<3.9]
    - safe-pysha3 >=1.0.0  # [py>=3.9]
  run_constrained:
    - pycryptodome >=3.6.6,<4
    - pysha3 >=1.0.0,<2.0.0  # [py<3.9]
    - safe-pysha3 >=1.0.0  # [py>=3.9]

test:
  imports:
    - eth_hash
    - eth_hash.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-hash
  summary: 'eth-hash: The Ethereum hashing function, keccak256, sometimes (erroneously) called sha3'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
