{% set name = "eth-hash" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d2411a403a0b0a62e8247b4117932d900ffb4c8c64b15f92620547ca5ce46be5

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
    - setuptools-markdown
  run:
    - python
    - pycryptodome >=3.6.6,<4
  run_constrained:
    - safe-pysha3 >=1.0.0  # [py>=3.10]
    - pysha3 >=1.0.0,<2.0.0  # [py<3.10]

test:
  imports:
    - eth_hash
    - eth_hash.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-hash
  summary: 'eth-hash: The Ethereum hashing function, keccak256, sometimes (erroneously) called sha3'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
